select * from products
  insert into Products values('C5100', 'Black Shirt with Beads','Women Clothes', 'Shirt','images\ladies\g6.jpg','Bareeze',20, 'A new trend with more style', 1300)
insert into Products values('C3210', 'Pink Embroided Kurta','Women Clothes', 'Shirt','images\ladies\g7.jpg','Asim Jofa',22, 'A new branded shirt with extra comfort', 1800)
insert into Products values('C7100', 'Orange Cotton Shirt','Women Clothes', 'Shirt','images\ladies\g7.png','Nishat Linen',30, 'A new trend with more style', 2300)
insert into Products values('C4500', 'Black Cotton Kurta','Women Clothes', 'Shirt','images\ladies\g8.jpg','Aramish',33, 'A new cool design!. Dont forget to try out!', 1500)
insert into Products values('C3309', 'Multi colored shirt','Women Clothes', 'Shirt','images\ladies\g9.jpg','Firdous Collection',12, 'New colors of spring! Most attractive one!', 3300)
insert into Products values('C2980', 'Red OffWhite Lawn','Women Clothes', 'Shirt','images\ladies\g10.jpg','Bonanza',17, 'A new branded kurta with extra comfort', 2700)
insert into Products values('C5600', 'BlueBlack Dotted Shirt','Women Clothes', 'Shirt','images\ladies\g12.jpg','Nishat Linen',43, 'A new branded shirt with modern design!', 2600)
insert into Products values('C9900', 'Black Coat','Women Clothes', 'Coat','images\ladies\g13.jpg','Bonanza',9, 'A new branded coat with extra comfort', 3700)
insert into Products values('C9800', 'Black Woolen Coat','Women Clothes', 'Coat','images\ladies\g14.jpg','Nishat Linen',12, 'A new branded coat with extra comfort', 3900)
insert into Products values('C1900', 'OffWhite Coat','Women Clothes', 'Coat','images\ladies\g17.jpg','Bonanza',33, 'A new branded coat with extra comfort', 4100)
insert into Products values('C8600', 'Grey Woolen Coat','Women Clothes', 'Coat','images\ladies\g18.jpg','Star Classic',16, 'A new branded coat with extra comfort', 3100)
insert into Products values('C4871', 'Red Woolen Coat','Women Clothes', 'Shirt','images\ladies\g19.jpg','Nishat Linen',12, 'A new branded coat with extra comfort', 3900)

------------------ men wear------------
insert into Products values('C2344','Blue check Shirt', 'Men Clothes', 'Shirt', 'images\men\m1.jpg','Asim Jofa', 20, 'Exellent quality! Must try.', 1200)
insert into Products values('C2345','Blue Cotton Shirt', 'Men Clothes', 'Shirt', 'images\men\m2.jpg','Bareeze', 12, 'Exellent quality! Must try.', 1600)
insert into Products values('C2346','Green Shirt', 'Men Clothes', 'Shirt', 'images\men\m3.jpg','Asim Jofa', 4, 'A new trend with soothing quality', 2200)
insert into Products values('C2347','Grey Kurta', 'Men Clothes', 'Kurta', 'images\men\m4.jpg','Asim Jofa', 29, 'Exellent quality fabric! Must try.', 2600)
insert into Products values('C2348','Off-White Kurta', 'Men Clothes', 'Kurta', 'images\men\m5.jpg','Bonanza', 14, 'Exellent quality! Must try.', 3200)
insert into Products values('C2349','White Kurta', 'Men Clothes', 'Kurta', 'images\men\m6.jpg','Asim Jofa', 10, 'A new trend with soothing quality', 3300)
insert into Products values('C2350','Black Kurta', 'Men Clothes', 'Kurta', 'images\men\m7.jpg','Asim Jofa', 20, 'Exellent quality! Must try.',2600)
insert into Products values('C2351','Brown Kurta', 'Men Clothes', 'Kurta', 'images\men\m8.jpg','Asim Jofa', 13, 'Exellent quality! Must try.', 3200)
insert into Products values('C2352','Blue Jeans', 'Men Clothes', 'Jeans', 'images\men\m9.jpg','Ahmed Fabrics', 33, 'A new fashion with extra style!', 2300)
insert into Products values('C2353','Light Blue Jeans', 'Men Clothes', 'Jeans', 'images\men\m10.jpg','Ahmed Fabrics', 20, 'Exellent quality! Must try.', 2300)
insert into Products values('C2354','Black Trendy Jeans', 'Men Clothes', 'Jeans', 'images\men\m9.jpg','Asim Jofa', 24, 'Exellent quality! Must try.', 2600)
insert into Products values('C2355','Black Coat', 'Men Clothes', 'Coat', 'images\men\m12.jpg','Ahmed Fabrics', 33, 'A new fashion with extra style!', 3300)
insert into Products values('C2356','White shirt', 'Men Clothes', 'Shirt', 'images\men\m13.jpg','Ahmed Fabrics', 24, 'Exellent quality! Must try.', 1500)

---------electrical ----
insert into Products values('E0101','White Electric Iron','Electrical Appliances','Iron','images\e1.jpg','Panasonic', 10,'consume less electricity with best quality!', 4500)
insert into Products values('E0102','Microwave Oven','Electrical Appliances','Electric Oven','images\e2.jpg','Samsung', 20,'Enjoy hot food in matter of minutes!', 7500)
insert into Products values('E0103','Black Electric Kettle','Electrical Appliances','Kettle','images\e3.jpg','Panasonic', 40,'consume less electricity with best quality!', 3500)
insert into Products values('E0104','Speakers','Electrical Appliances','Speakers','images\e4.jpg','Panasonic', 10,'Echoes Perfectly!', 8000)
insert into Products values('E0105','White Washing Machine','Electrical Appliances','Washing Machine','images\e5.jpg','Haier', 39,'Brighten your clothes with less electricity!', 32000)
insert into Products values('E0106','Hair Drier','Electrical Appliances','Hair','images\e8.jpg','Panasonic', 20,'consume less electricity with best quality!', 2700)
insert into Products values('E0109','Electric Heater','Electrical Appliances','Heater','images\e9.jpg','LG', 10,'consume less electricity with best quality!', 13000)
insert into Products values('E0110','White Fan','Electrical Appliances','Fan','images\e10.jpg','Haier', 10,'consume less electricity with best quality!', 7000)


---cosmetics
insert into Products values('C0101','Pink Lipstick','Cosmetics','Lipstick','images\c1.jpg','Medora', 12,'Enhance beauty with attractive color!', 900)
insert into Products values('C0102','Black Eyeliner','Cosmetics','eyeliner','images\c2.jpg','Revlon', 33,'Enhance beauty with attractive color!', 700)
insert into Products values('C0103','Multi Colored Blushes','Cosmetics','BlushOn','images\c3.jpg','Medora', 23,'Enhance beauty with attractive color!', 2500)
insert into Products values('C0104','Light theme blush On','Cosmetics','BlushOn','images\c4.jpg','Maybelline', 12,'Enhance beauty with attractive color!', 1300)
insert into Products values('C0105','MakeUp Brush Pack','Cosmetics','Brush','images\c5.jpg','Medora', 12,'Enhance beauty with attractive color!', 900)
insert into Products values('C0106','Red NailPolish','Cosmetics','NailPolish','images\c6.jpg','Medora', 33,'Enhance beauty with attractive color!', 700)
insert into Products values('C0107','Black NailPolish','Cosmetics','NailPolish','images\c7.jpg','Medora', 24,'Enhance beauty with attractive color!', 7600)
insert into Products values('C0108','Orange NailPolish','Cosmetics','NailPolish','images\c8.jpg','Medora', 55,'Enhance beauty with attractive color!', 980)
insert into Products values('C0109','Red Lipstick','Cosmetics','Lipstick','images\c9.jpg','LOrel', 36,'Enhance beauty with attractive color!', 1200)
insert into Products values('C0110','Blue Lipstick','Cosmetics','Lipstick','images\c10.jpg','LOreal', 6,'Enhance beauty with attractive color!', 1200)
insert into Products values('C0111','Skin Shade Face Powder','Cosmetics','FacePowder','images\c11.jpg','Medora', 33,'Enhance beauty with delightful shade!', 2200)
insert into Products values('C0112','Dark Shade Face Powder','Cosmetics','FacePowder','images\c12.jpg','Maybelline', 23,'With enhanced quality!', 2500)
insert into Products values('C0113','Brush Pack','Cosmetics','Brush','images\c13.jpg','Medora', 27,'Give more lush factors!', 3000)
insert into Products values('C0114','Different size brushes','Cosmetics','Brush','images\c14.jpg','Urban Decay', 34,'Enhance beauty with attractive color!', 3500)


----- jewelry----------\
insert into Products values('J0101','Silver Plated Bangles','Jewelry','Bangle','images\j1.jpg','Michele', 23, 'Ravishing bangles increase hand beauty!', 5000)
insert into Products values('J0102','Mutli Colored Rings','Jewelry','Rings','images\j2.jpg','Michele', 23, 'Ravishing rings increase hand beauty!', 5000)
insert into Products values('J0103','Diamond Rings','Jewelry','Rings','images\j3.jpg','Ritani', 12, 'Perfectly designed product matches your taste!', 5000)
insert into Products values('J0104','Golden Necklace','Jewelry','Necklace','images\j4.jpg','Ritani', 10, 'Increases your beauty!', 2300)
insert into Products values('J0105','Blue Silver Earrings','Jewelry','Earrings','images\j5.jpg','Michele', 13, 'Ravishing Earrings satsify your atrractiveness!', 4000)
insert into Products values('J0106','Golden Earrings','Jewelry','Earrings','images\j6.jpg','Michele', 23, 'Ravishing Earrings satsify your atrractiveness!', 4500)
insert into Products values('J0107','Red Bead Necklace','Jewelry','Necklace','images\j7.jpg','Ritani', 12, 'Mild attractive features. Must try!', 5500)
insert into Products values('J0108','White design Green Necklace','Jewelry','Necklace','images\j8.jpg','Michele', 26, 'Mild attractive features. Must try!', 5700)
insert into Products values('J0109','White bead bracelet','Jewelry','Bangle','images\j9.jpg','OMI', 22, 'Must match your beauty .Try out this one!', 2400)
insert into Products values('J0110','Silver luxurious bangle','Jewelry','Bangle','images\j10.jpg','OMI', 5, 'Ravishing bangles increase hand beauty!', 2360)
insert into Products values('J0111','White plated bracelet','Jewelry','Bangle','images\j11.jpg','Michele', 12, 'New design , eye catching hand wear!', 4500)
insert into Products values('J0112','Green beauty bangle','Jewelry','Bangle','images\j12.jpg','Michele', 55, 'New in market with fabulous looks!', 1200)

